services:
  server:
    container_name: elevenlabs_server
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./server:/app/server
    networks:
      - elevenlabs_net

  client:
    container_name: elevenlabs_client
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8502:8501"
    environment:
      - BACKEND_URL=http://elevenlabs_server:5000/api/speak
    depends_on:
      - server
    volumes:
      - ./client:/app/client
    networks:
      - elevenlabs_net

networks:
  elevenlabs_net:
    driver: bridge
